version: '3.9'

services:
  oracle-db:
    build:
      dockerfile: ./Dockerfile
      context: ./dockerfile-sample-builder
    container_name: ora-database
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PWD=bikewake
      - ORACLE_PDB=BikeWakePlugableDatabase
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "8080:8080"
    volumes:
      - ora-bikewake-data:/opt/oracle/oradata

volumes:
  ora-bikewake-data:
 
    
